# src/main/resources/application.yml
spring:
  datasource:
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://localhost:5432/minicinema
    username: developer
    password: cinema@123
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    mode: HTML5
    encoding: UTF-8

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    com.maoyan: debug


